### ISSUE TITLE
Writing an Event by "record.EventRecorder" leads to panic

### ISSUE THREAD

**Issue by DeamonMV** [DeamonMV/static-webpage-k8s-operator#1]
This code lead to panic 

```
r.Recorder.Event(nil, "Warning", "Deleting",
    fmt.Sprintf("Custom Resource %s is being deleted from the namespace %s", cr.Name, cr.Namespace))
```

Operator log:

```
1.6765515004452665e+09  INFO    Starting EventSource    {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "source": "kind source: *v1alpha1.Static"}
1.6765515004453268e+09  INFO    Starting EventSource    {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "source": "kind source: *v1.Deployment"}
1.6765515004453387e+09  INFO    Starting Controller     {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static"}
1.6765515004454129e+09  DEBUG   events  static-webpage-k8s-operator-controller-manager-bdff6546c-47cqj_74400c5a-7193-4271-afb4-2eb0ac559872 became leader       {"type": "Normal", "object": {"kind":"Lease","namespace":"static-webpage-k8s-operator-system","name":"6851ba50.daemon.io","uid":"58445e5c-7a55-46b4-8a6f-bf70403c19d1","apiVersion":"coordination.k8s.io/v1","resourceVersion":"563597"}, "reason": "LeaderElection"}
1.6765515005466266e+09  INFO    Starting workers        {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "worker count": 2}
1.6765515005468068e+09  INFO    Performing Finalizer Operations for Webpage before delete CR    {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "a5aa3358-ab61-406b-8d72-fc06007c4c12"}
1.6765515005529573e+09  INFO    Do some finalization    {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "a5aa3358-ab61-406b-8d72-fc06007c4c12"}
1.676551500552984e+09   INFO    Before Event message    {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "a5aa3358-ab61-406b-8d72-fc06007c4c12"}
1.67655150055301e+09    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "a5aa3358-ab61-406b-8d72-fc06007c4c12"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13998c0]

goroutine 238 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x14d7f00, 0x235bd50})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/DeamonMV/static-webpage-k8s-operator/controllers.(*StaticReconciler).Reconcile(0xc00082be90, {0x18d6c58, 0xc000673e90}, {{{0xc000646360?, 0x10?}, {0xc0001cbb10?, 0x40dae7?}}})
        /workspace/controllers/static_controller.go:185 +0x1180
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x18d6bb0?, {0x18d6c58?, 0xc000673e90?}, {{{0xc000646360?, 0x15daf20?}, {0xc0001cbb10?, 0x4045d4?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003de960, {0x18d6bb0, 0xc000844dc0}, {0x1528220?, 0xc000432020?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003de960, {0x18d6bb0, 0xc000844dc0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x333
```

**Comment by DeamonMV** [comment]
Solved:

`main.go` - `Recorder: mgr.GetEventRecorderFor("webpage-controller"),`
```
	if err = (&controllers.StaticReconciler{
		Client:   mgr.GetClient(),
		Scheme:   mgr.GetScheme(),
		Recorder: mgr.GetEventRecorderFor("webpage-controller"),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Webpage")
		os.Exit(1)
	}
```
